# Generated by Django 4.1 on 2022-09-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0006_alter_employee_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='profile_pic',
            new_name='picture',
        ),
    ]
