# Generated by Django 4.1 on 2022-09-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0007_rename_profile_pic_employee_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.FileField(default='none', upload_to='media/images'),
        ),
    ]
