# Generated by Django 4.1 on 2022-09-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0009_remove_employee_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.FileField(default='', upload_to='media/images'),
        ),
    ]
